language: node_js

cache:
  directories:
    - ~/.npm
    - "node_modules"

node_js:
  - '13'

services:
  - mongodb

git:
  depth: 3

branches:
  only:
    - master

env:
  global:
    - NODE_ENV=test
    - PORT=3000
    - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy5
    - JWT_EXPIRATION_MINUTES=15
    - MONGODB_URI=mongodb://localhost:27017/coeus
    - REDIS_HOST=redis-15047.c89.us-east-1-3.ec2.cloud.redislabs.com
    - REDIS_PASS=1234
    - REDIS_PORT=15047
    - EXPRESS_SESSION_SECRET=C6369AD13051EB8986C6EE3F9617F31D9
    - COOKIE_SECRET=C6369AD13051EB8986C6EE3F9617F5199
    - COOKIE_EXPIRATION_IN_DAYS=7
    - JWT_EXPIRATION_IN_DAYS=7

script:
  - yarn
  - yarn build
  - yarn test
