language: node_js

cache:
  directories:
    - ~/.npm
    - "node_modules"

node_js:
  - '13'

services:
  - mongodb
  - redis-server

git:
  depth: 3

branches:
  only:
    - master

env:
  global:
    - PORT=3000
    - JWT_SECRET=bA2xcjpf8y5aSUFsNB2qN5yymUBSs6es3qHoFpGkec75RCeBb8cpKauGefw5qy5
    - JWT_EXPIRATION_MINUTES=15
    - EXPRESS_SESSION_SECRET=C6369AD13051EB8986C6EE3F9617F31D9
    - COOKIE_SECRET=C6369AD13051EB8986C6EE3F9617F5199
    - COOKIE_EXPIRATION_IN_DAYS=7
    - JWT_EXPIRATION_IN_DAYS=7

script:
  - yarn
  - yarn build
  - yarn test
