image: ubuntu
environment:
  matrix:
  # node.js
  - nodejs_version: "12"

# Install scripts. (runs after repo cloning)
install:
  - npm install

# Post-install test scripts.
test_script:
  # run tests
  - npm run mocha

# Don't actually build.
build: off
services:
  - mongodb
  - redis