image: ubuntu
# Test against this version of Node.js
stack: node 12, mongodb, redis
environment:
# Install scripts. (runs after repo cloning)
install:
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # run tests
  - npm run mocha

# Don't actually build.
build: off