version: '3.5'

services:
  coeus:
    container_name: coeus
    restart: always
    image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo/coeus
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASS=
      - NODE_ENV=production
      - PORT=3000
    links:
      - redis
      - mongo
    tty: true
  mongo:
    image: mongo:latest
    container_name: coeus-mongo
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongo:/data/db
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

volumes:
  mongo:
  redis:
