version: '3.5'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    tty: true
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-passwd}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-database}
    volumes:
      - mongo:/data/db
    networks:
      - mongo

  redis:
    image: redis
    restart: always
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - redis

volumes:
  mongo:

networks:
  mongo:
    driver: bridge
  redis:
    driver: bridge