name: Build

on: 
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: ESLint checks
      uses: gimenete/eslint-action@1.0
    - name: npm install, build, and test
      run: |
        npm install
        npm run dev
        npm run mocha
      env:
        CI: true
