name: Shed And Breakfast

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env: # Or as an environment variable
        JWT_SECRET: "r69+T3ExQgCbWzHF8u+SJetNPGMBDe30"
        COOKIE_SECRET: "C6369AD13051EB8986C6EE3F9617F5199"
        EXPRESS_SESSION_SECRET: "C6369AD13051EB8986C6EE3F9617F31D9"
        COOKIE_EXPIRATION_IN_DAYS: "7"
        JWT_EXPIRATION_IN_DAYS: "7"
        MONGODB_URI: ${{ secrets.MONGODB_URI }}  
        ON_HEROKU: true
    - name: Install deps build and test
      run: |
        npm install
        npm run test
      env:
        CI: true
